# Generated by Django 5.1.3 on 2024-12-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_customer_manager_staff_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('staff', 'Staff'), ('manager', 'Manager')], default='manager', max_length=10),
        ),
    ]
