# Generated by Django 5.1.3 on 2024-12-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0014_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='diachi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='hovaten',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='sdt',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
