# Generated by Django 5.1.3 on 2024-12-07 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0016_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
